name: GetChangelogEntry
permissions:
  pull-requests: write
  contents: write
jobs:
  pull-commit-message:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      continue-on-error: true
    - name: get merge commit message
      id: pull
      run: "pull_number=\"$(jq --raw-output .pull_request.number \"$GITHUB_EVENT_PATH\")\" \ncommit_message=\"$(git log --pretty=\"format:%b\")\"\necho message=\"$commit_message [GH-$pull_number]\"  >> $GITHUB_OUTPUT\n"
    - name: GARALT debug probe
      run: |-
        printf '%s\n' 'GARALT_DBG extracted_message_value:'
        msg_val=$(printf '%s' "${{ toJSON(steps.pull.outputs.message) }}")
        printf '%s\n' "${msg_val}"
      continue-on-error: true
    - name: Save changelog entry
      env:
        CHANGELOG_ENTRY: ${{ steps.pull.outputs.message }}
      run: |
        echo "$CHANGELOG_ENTRY" > changelog_entry.txt
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: changelog_entry
        path: changelog_entry.txt
        overwrite: true
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  pull_request:
    types:
    - closed
