---
name: Generation Check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gencheck.yaml'
      - '**.go'

concurrency:
  group: 'gencheck-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  gencheck:
    runs-on: custom-linux-large
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Trigger Failure
      run: exit 1    needs: gencheck
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
  comment-on-fail:
    needs: gencheck
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
