name: Generation Check
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: gencheck-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  gencheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Trigger Failure
      run: exit 1
  save-artifacts-on-fail:
    needs: gencheck
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml
    secrets: inherit
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  pull_request:
    types:
    - opened
    - synchronize
    paths:
    - .github/workflows/gencheck.yaml
    - '**.go'
