name: Terraform Schema Linting
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/tflint.yaml'
      - 'vendor/**'
      - '**.go'
jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  save-artifacts-on-fail:
    needs: tflint
    if: failure()
    uses: ./.github/workflows/save-artifacts.yaml
